POST http://localhost:3000/search/
Content-Type: application/json

{
    "keyword": "melbourne"
}

###
POST http://localhost:3000/search/tech
Content-Type: application/json

{
    "techStack": ["HTML", "JavaScript"]
}

###
POST http://localhost:3000/search/location
Content-Type: application/json

{
    "location:": "Melbourne"
}