const Candidate = require('./Candidate')


const candidates = [
    {
        firstName: 'Mill',
        lastName: 'Smith ',
        phoneNumber: '0450890999',
        emailAddress: 'mill@example.com ',
        location: 'Melbourne',
        currentJobTitle: 'Java Developer',
        CurrentEmployer: 'Google',
        roleType: 'Permanent',
        responsibilities: 'Senior Engineer',
        minSalary: 180000,
        expectedJobTitle: 'Senior Engineer',
        techStack: ['javascript', 'ruby', 'rails', 'mongodb', 'mongoose', 'SQLdb', 'JAVA'],
        contactSource: 'linkedIn',
        clientNotes: 'An excellent candidate',
        personalNotes: 'This guy is awesome',
        priority: ['MONEY'],
        expectedCompany: ['Amazon'],
        resumeUrl: ' ',
        isActive: true,
        createdAt: new Date('15 July 2018'),
        updatedAt: new Date('16 July 2018')
    },
    {
        firstName: 'Jonathan',
        lastName: 'Anders ',
        phoneNumber: '0412985777',
        emailAddress: 'mailer@example.com ',
        location: 'Perth',
        currentJobTitle: 'Senior Developer',
        CurrentEmployer: 'Amplify',
        roleType: 'Permanent',
        responsibilities: 'teaching juniors, code review, manage project',
        minSalary: 180000,
        expectedJobTitle: 'Chief Technology Officer',
        techStack: ['Python', 'C#', '.NET', 'MongoDB', 'Django', 'SQL', 'Node'],
        contactSource: 'linkedIn',
        clientNotes: 'Highly passionate and driven',
        personalNotes: 'This guy is awesome',
        priority: ['MONEY'],
        expectedCompany: ['Amazon'],
        resumeUrl: ' ',
        isActive: true,
        createdAt: new Date('15 July 2018'),
        updatedAt: new Date('16 July 2018')
    },
    {
        firstName: 'Linda',
        lastName: 'Wong ',
        phoneNumber: '0412985777',
        emailAddress: 'linda@example.com ',
        location: 'Sydney',
        currentJobTitle: 'Web Developer',
        CurrentEmployer: 'Westpac',
        roleType: 'Permanent',
        responsibilities: 'unit testing, code review, manage project',
        minSalary: 180000,
        expectedJobTitle: 'Senior Developer',
        techStack: ['C++', 'C#', '.NET', 'MongoDB', 'Java', 'SQL', 'Node', 'React'],
        contactSource: 'linkedIn',
        clientNotes: 'Highly passionate and driven',
        personalNotes: 'This gal is awesome',
        priority: ['MONEY'],
        expectedCompany: ['Amazon'],
        resumeUrl: ' ',
        isActive: true,
        createdAt: new Date('15 July 2018'),
        updatedAt: new Date('16 July 2018')
    },
    {
        firstName: 'Jane',
        lastName: 'Foster ',
        phoneNumber: '0412985777',
        emailAddress: 'jane@example.com ',
        location: 'Melbourne',
        currentJobTitle: 'Junior Developer',
        CurrentEmployer: 'Coder Academy',
        roleType: 'Permanent',
        responsibilities: 'unit testing, code review, manage project',
        minSalary: 180000,
        expectedJobTitle: 'Mid-level Developer',
        techStack: ['JavaScript', 'C#', '.NET', 'MongoDB', 'Java', 'SQL', 'Node', 'React', 'Express'],
        contactSource: 'linkedIn',
        clientNotes: 'Highly passionate and driven',
        personalNotes: 'This gal is awesome',
        priority: ['MONEY'],
        expectedCompany: ['Amazon'],
        resumeUrl: ' ',
        isActive: true,
        createdAt: new Date('15 July 2018'),
        updatedAt: new Date('16 July 2018')
    }
]
Candidate.create(candidates)
    .then(()=> {
        console.info('seeded candidates');
    })