const Candidate = require('./Candidate')


const candidates = [
    {
        techStack: [
            "JavaScript",
            "Python",
            "Ruby on Rails",
            "Ruby",
            "HTML",
            "CSS",
            "Node.js",
            "React",
            "Express",
            "AWS"
        ],
        priority: [
            "Technologies",
            "Salary",
            "Location",
            "Job Title",
            "Role Responsibilities",
            "Training and Professional Development",
            "The Team",
            "Office Environment",
            "The Company’s Purpose and Products",
            "Management",
            "The Hours",
            "Ability to work from home",
            "Travel (work related as a consistent part of the role)"
        ],
        expectedCompany: [
            "Start Ups",
            "Enterprise Companies",
            "Technology Companies",
            "Government"
        ],
        "minSalary":65,
        "firstName":"Maurice",
        "lastName":"Yong",
        "phoneNumber":"431531500",
        "emailAddress":"snikeron@yahoo.com",
        "location":"Melbourne",
        "currentJobTitle":"Unemployed",
        "currentEmployer":"Myself",
        "roleType":"Permanent",
        "responsibilities":"Doing absolutely nothing",
        "expectedJobTitle":"Junior Web Developer, Graduate Engineer, Associate",
        "expectedRoleType":"Either",
        "contactSource":"LinkedIn",
        "clientNotes":"",
        "personalNotes":"",
        "resumeUrl":"https://encode-resumes.s3.amazonaws.com/1532486449277-lg.pdf",
        "isActive":true,
    },
    {
        techStack: [
            "JavaScript",
            "Python",
            "Ruby on Rails",
            "Ruby",
            "HTML",
            "CSS",
            "Node.js",
            "React",
            "Express",
            "AWS"
        ],
        priority: [
            "Technologies",
            "Salary",
            "Location",
            "Job Title",
            "Role Responsibilities",
            "Training and Professional Development",
            "The Team",
            "Office Environment",
            "The Company’s Purpose and Products",
            "Management",
            "The Hours",
            "Ability to work from home",
            "Travel (work related as a consistent part of the role)"
        ],
        expectedCompany: [
            "Start Ups",
            "Enterprise Companies",
            "Technology Companies",
            "Government"
        ],
        "minSalary":65,
        "firstName":"Jimmy",
        "lastName":"Barnes",
        "phoneNumber":"0419324183",
        "emailAddress":"jimmy@developer.com",
        "location":"Perth",
        "currentJobTitle":"Mid-level Software Engineer",
        "currentEmployer":"Intracorp",
        "roleType":"Permanent",
        "responsibilities":"Writing unit tests and coaching juniors",
        "expectedJobTitle":"Senior Web Developer, Senior Engineer",
        "expectedRoleType":"Either",
        "contactSource":"LinkedIn",
        "clientNotes":"Jimmy is passionate about teaching and coaching juniors",
        "personalNotes":"Mentioned that he is talking at the next LevelsConf 2019",
        "resumeUrl":"https://encode-resumes.s3.amazonaws.com/1532486449277-lg.pdf",
        "isActive":true,
    },
    {
        techStack: [
            "JavaScript",
            "Python",
            "Ruby on Rails",
            "Ruby",
            "HTML",
            "CSS",
            "Node.js",
            "React",
            "Express",
            "AWS"
        ],
        priority: [
            "Technologies",
            "Salary",
            "Location",
            "Job Title",
            "Role Responsibilities",
            "Training and Professional Development",
            "The Team",
            "Office Environment",
            "The Company’s Purpose and Products",
            "Management",
            "The Hours",
            "Ability to work from home",
            "Travel (work related as a consistent part of the role)"
        ],
        expectedCompany: [
            "Start Ups",
            "Enterprise Companies",
            "Technology Companies",
            "Government"
        ],
        "minSalary":125,
        "firstName":"Linda",
        "lastName":"Johnson",
        "phoneNumber":"0486392754",
        "emailAddress":"linda@developer.com",
        "location":"Brisbane",
        "currentJobTitle":"Senior Engineer",
        "currentEmployer":"Google",
        "roleType":"Permanent",
        "responsibilities":"Making coffee for my juniors and writing devastatingly good code",
        "expectedJobTitle":"CTO",
        "expectedRoleType":"Permanent",
        "contactSource":"Word of mouth",
        "clientNotes":"",
        "personalNotes":"",
        "resumeUrl":"https://encode-resumes.s3.amazonaws.com/1532486449277-lg.pdf",
        "isActive":true,
    }
]
Candidate.create(candidates)
    .then(()=> {
        console.info('seeded candidates');
    })