POST http://localhost:3000/candidates
Content-Type: application/json

{
    "firstName": "Andrew",
    "lastName": "Smith",
    "phoneNumber": "0450890999",
    "emailAddress": "mill@example.com",
    "location": "Melbourne",
    "currentJobTitle": "Java Developer",
    "CurrentEmployer": "Google",
    "roleType": "Permanent",
    "responsibilities": "Senior Engineer",
    "technologies": ["javascript"],
    "minSalary": 180000,
    "expectedJobTitle": "Senior Engineer",
    "techStack": ["ruby"],
    "contactSource": "linkedIn",
    "clientNotes": "An excellent candidate",
    "personalNotes": "This guy is awesome",
    "priority": ["MONEY"],
    "expectedCompany": ["Amazon"],
    "resumeUrl": " ",
    "isActive": true,
    "createdAt": "2018-07-17",
    "updatedAt": "2018-07-17"
}

###
GET https://backend-bzorbvezmq.now.sh/candidates

###
PUT http://localhost:3000/candidates/5b5023ada851b545528b755d
Content-Type: application/json

{
    "clientNotes": "Testing put route!!"
}

###
GET http://localhost:3000/candidates/5b5023ada851b545528b755d